services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=demo-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ=Asia/Tokyo
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres:
