name: test

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test

jobs:
  jest-test:
    name: Jest Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install packages
        run: npm ci

      - name: Run tests
        run: npx nx run-many --target=test --codeCoverage=true 
  deploy:
    needs: jest-test
    if: ${{ success() }}
    steps:
      - name: Deploy Client Service
        uses: ttskch/render-deploy@v1.0.0
        with:
          api-key: ${{ secrets.RENDER_API_KEY }}
          service-id: ${{ secrets.RENDER_SERVICE_ID_CLIENT }}
          interval: 20 # optional
          timeout: 600 # optional
      - name: Deploy API Service
        uses: ttskch/render-deploy@v1.0.0
        with:
          api-key: ${{ secrets.RENDER_API_KEY }}
          service-id: ${{ secrets.RENDER_SERVICE_ID_API }}
          interval: 20 # optional
          timeout: 600 # optional